turtle_manager:
  ros__parameters:
    turtlesim_screen_max: 11.0
    turtlesim_screen_min: 0.0
    screen_color_limit: 5.5
    letter_height: 3.0
    letter_with: 5.0
    screen_color: [69, 86, 255]
    line_default_color: [255,255,255]
    line_widht: 3

goto_action_server:
  ros__parameters:
    angular_tolerance: 0.1
    distance_tolerance: 0.01
    kp_dist: 1.5
    kp_angle: 2.0
    max_angular_vel: 5.0